/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.UsuarioDAO;
import DTO.UsuarioDTO;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lucas
 */
public class frmCadastroVIEW extends javax.swing.JFrame {

    /**
     * Creates new form frmCadastroVIEW
     */
    public frmCadastroVIEW() {
        initComponents();
        listarValores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel2 = new com.raven.swing.RoundPanel();
        label1 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        roundPanel1 = new com.raven.swing.RoundPanel();
        label6 = new java.awt.Label();
        txtNomeCad = new java.awt.TextField();
        btnCadastroSistema = new java.awt.Button();
        label26 = new java.awt.Label();
        txtEndCad = new java.awt.TextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        btnCarregarCampos = new java.awt.Button();
        btnLimparValores = new java.awt.Button();
        btnAlterarCampos = new java.awt.Button();
        btnExcluirRegistros = new java.awt.Button();
        btnExcluirTudo = new java.awt.Button();
        label27 = new java.awt.Label();
        cbSexoCad = new javax.swing.JComboBox<>();
        label28 = new java.awt.Label();
        cbCargoCad = new javax.swing.JComboBox<>();
        label29 = new java.awt.Label();
        txtCpfCad = new java.awt.TextField();
        label30 = new java.awt.Label();
        txtRgCad = new java.awt.TextField();
        label31 = new java.awt.Label();
        txtTelCad = new java.awt.TextField();
        label32 = new java.awt.Label();
        txtCelCad = new java.awt.TextField();
        label33 = new java.awt.Label();
        cbSetorCad = new javax.swing.JComboBox<>();
        label34 = new java.awt.Label();
        cbCnhCad = new javax.swing.JComboBox<>();
        label35 = new java.awt.Label();
        txtIdadeCad = new java.awt.TextField();
        label36 = new java.awt.Label();
        txtEmailCad = new java.awt.TextField();
        label37 = new java.awt.Label();
        cbContratoCad = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(2147483647, 1947483447));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundPanel2.setBackground(new java.awt.Color(51, 51, 51));
        roundPanel2.setForeground(new java.awt.Color(51, 51, 51));

        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Gotham", 1, 36)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setMaximumSize(new java.awt.Dimension(40000, 32767));
        label1.setPreferredSize(new java.awt.Dimension(80, 40));
        label1.setText("CADASTRO");

        jLabel1.setFont(new java.awt.Font("Gotham", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("POR LUCAS GONÇALVES DE OLIVEIRA MARTINS");

        javax.swing.GroupLayout roundPanel2Layout = new javax.swing.GroupLayout(roundPanel2);
        roundPanel2.setLayout(roundPanel2Layout);
        roundPanel2Layout.setHorizontalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(447, Short.MAX_VALUE))
                    .addGroup(roundPanel2Layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(83, 83, 83))))
        );
        roundPanel2Layout.setVerticalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(roundPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        roundPanel1.setBackground(new java.awt.Color(153, 153, 153));

        label6.setFont(new java.awt.Font("Gotham", 1, 14)); // NOI18N
        label6.setForeground(new java.awt.Color(255, 255, 255));
        label6.setText("Nome:");

        txtNomeCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeCadActionPerformed(evt);
            }
        });

        btnCadastroSistema.setBackground(new java.awt.Color(51, 51, 51));
        btnCadastroSistema.setFont(new java.awt.Font("Gotham", 1, 18)); // NOI18N
        btnCadastroSistema.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastroSistema.setLabel("Cadastrar");
        btnCadastroSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroSistemaActionPerformed(evt);
            }
        });

        label26.setFont(new java.awt.Font("Gotham", 1, 14)); // NOI18N
        label26.setForeground(new java.awt.Color(255, 255, 255));
        label26.setText("Endereço:");

        txtEndCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEndCadActionPerformed(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Endereço", "Sexo", "Cargo", "CPF", "RG", "CNH", "Telefone", "Celular", "Setor", "Idade", "Email", "Contrato"
            }
        ));
        jTable.setAlignmentX(1);
        jTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jTable);

        btnCarregarCampos.setBackground(new java.awt.Color(51, 51, 51));
        btnCarregarCampos.setFont(new java.awt.Font("Gotham", 1, 18)); // NOI18N
        btnCarregarCampos.setForeground(new java.awt.Color(255, 255, 255));
        btnCarregarCampos.setLabel("Carregar Campos");
        btnCarregarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarCamposActionPerformed(evt);
            }
        });

        btnLimparValores.setBackground(new java.awt.Color(51, 51, 51));
        btnLimparValores.setFont(new java.awt.Font("Gotham", 1, 18)); // NOI18N
        btnLimparValores.setForeground(new java.awt.Color(255, 255, 255));
        btnLimparValores.setLabel("X");
        btnLimparValores.setName("btnLimpar"); // NOI18N
        btnLimparValores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparValoresActionPerformed(evt);
            }
        });

        btnAlterarCampos.setBackground(new java.awt.Color(51, 51, 51));
        btnAlterarCampos.setFont(new java.awt.Font("Gotham", 1, 18)); // NOI18N
        btnAlterarCampos.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterarCampos.setLabel("Alteração");
        btnAlterarCampos.setName("btnAlterarValores"); // NOI18N
        btnAlterarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarCamposActionPerformed(evt);
            }
        });

        btnExcluirRegistros.setBackground(new java.awt.Color(51, 51, 51));
        btnExcluirRegistros.setFont(new java.awt.Font("Gotham", 1, 18)); // NOI18N
        btnExcluirRegistros.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirRegistros.setLabel("Excluir Registro");
        btnExcluirRegistros.setName("btnExcluirValores"); // NOI18N
        btnExcluirRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirRegistrosActionPerformed(evt);
            }
        });

        btnExcluirTudo.setBackground(new java.awt.Color(51, 51, 51));
        btnExcluirTudo.setFont(new java.awt.Font("Gotham", 1, 18)); // NOI18N
        btnExcluirTudo.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirTudo.setLabel("Excluir Tudo");
        btnExcluirTudo.setName("btnExcluirTudo"); // NOI18N
        btnExcluirTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirTudoActionPerformed(evt);
            }
        });

        label27.setFont(new java.awt.Font("Gotham", 1, 14)); // NOI18N
        label27.setForeground(new java.awt.Color(255, 255, 255));
        label27.setText("Sexo:");

        cbSexoCad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Feminino", "Masculino", "Outro" }));

        label28.setFont(new java.awt.Font("Gotham", 1, 14)); // NOI18N
        label28.setForeground(new java.awt.Color(255, 255, 255));
        label28.setText("Cargo:");

        cbCargoCad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Recepcionista", "Telefonista", "Gerente de Projetos", "Tech Lead Júnior", "Tech Lead Sênior", "Tech Lead Pleno", "Desenvolvedor Front-End Júnior", "Desenvolvedor Front-End Sênior", "Desenvolvedor Front-End Pleno", "Desenvolvedor Python Júnior", "Desenvolvedor Python Sênior", "Desenvolvedor Python Pleno", "Desenvolvedor Java Júnior", "Desenvolvedor Java Sênior", "Desenvolvedor Java Pleno", "Desenvolvedor Kotlin Júnior", "Desenvolvedor Kotlin Sênior", "Desenvolvedor Kotlin Pleno", "Desenvolvedor IOS Júnior", "Desenvolvedor IOS Sênior", "Desenvolvedor IOS Pleno" }));

        label29.setFont(new java.awt.Font("Gotham", 1, 14)); // NOI18N
        label29.setForeground(new java.awt.Color(255, 255, 255));
        label29.setText("RG:");

        txtCpfCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfCadActionPerformed(evt);
            }
        });

        label30.setFont(new java.awt.Font("Gotham", 1, 14)); // NOI18N
        label30.setForeground(new java.awt.Color(255, 255, 255));
        label30.setText("CPF:");

        txtRgCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRgCadActionPerformed(evt);
            }
        });

        label31.setFont(new java.awt.Font("Gotham", 1, 14)); // NOI18N
        label31.setForeground(new java.awt.Color(255, 255, 255));
        label31.setText("Telefone:");

        txtTelCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelCadActionPerformed(evt);
            }
        });

        label32.setFont(new java.awt.Font("Gotham", 1, 14)); // NOI18N
        label32.setForeground(new java.awt.Color(255, 255, 255));
        label32.setText("Celular:");

        txtCelCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelCadActionPerformed(evt);
            }
        });

        label33.setFont(new java.awt.Font("Gotham", 1, 14)); // NOI18N
        label33.setForeground(new java.awt.Color(255, 255, 255));
        label33.setText("Setor:");

        cbSetorCad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Técnico", "Administrativo", "Financeiro" }));

        label34.setFont(new java.awt.Font("Gotham", 1, 14)); // NOI18N
        label34.setForeground(new java.awt.Color(255, 255, 255));
        label34.setText("CNH:");

        cbCnhCad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "AB", "B", "C", "D", "E", "Não Possui" }));

        label35.setFont(new java.awt.Font("Gotham", 1, 14)); // NOI18N
        label35.setForeground(new java.awt.Color(255, 255, 255));
        label35.setText("Idade:");

        txtIdadeCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdadeCadActionPerformed(evt);
            }
        });

        label36.setFont(new java.awt.Font("Gotham", 1, 14)); // NOI18N
        label36.setForeground(new java.awt.Color(255, 255, 255));
        label36.setText("Email:");

        txtEmailCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailCadActionPerformed(evt);
            }
        });

        label37.setFont(new java.awt.Font("Gotham", 1, 14)); // NOI18N
        label37.setForeground(new java.awt.Color(255, 255, 255));
        label37.setText("Contrato:");

        cbContratoCad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CLT", "Terceirizado" }));

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addComponent(btnCarregarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimparValores, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluirRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluirTudo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 69, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel1Layout.createSequentialGroup()
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(roundPanel1Layout.createSequentialGroup()
                                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCadastroSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEndCad, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNomeCad, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addGroup(roundPanel1Layout.createSequentialGroup()
                                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbCnhCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, roundPanel1Layout.createSequentialGroup()
                                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(label27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                        .addComponent(label28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cbSexoCad, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbCargoCad, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(32, 32, 32)
                                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRgCad, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCpfCad, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(roundPanel1Layout.createSequentialGroup()
                                        .addComponent(label31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(89, 89, 89)
                                        .addComponent(label35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(roundPanel1Layout.createSequentialGroup()
                                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTelCad, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(label32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCelCad, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(label33, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbSetorCad, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(30, 30, 30)
                                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbContratoCad, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(label37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEmailCad, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(label36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtIdadeCad, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(22, 22, 22))))
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEndCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(roundPanel1Layout.createSequentialGroup()
                            .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cbSexoCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCpfCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(txtTelCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addComponent(label35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtIdadeCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(cbCargoCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmailCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtCelCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtRgCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnCadastroSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(roundPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(roundPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbCnhCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbSetorCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbContratoCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCarregarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimparValores, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirTudo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(182, 182, 182))
        );

        getContentPane().add(roundPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 83, -1, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**/
    private void btnCadastroSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroSistemaActionPerformed
        String nome_funcionario, endereco_funcionario;
        String cargo_funcionario, cel_funcionario, cnh_funcionario, contrato_funcionario, cpf_funcionario, email_funcionario, idade_funcionario, rg_funcionario, setor_funcionario, sexo_funcionario, tel_funcionario;
        nome_funcionario = txtNomeCad.getText();
        endereco_funcionario = txtEndCad.getText();
        cargo_funcionario = cbCargoCad.getSelectedItem().toString();
        cel_funcionario = txtCelCad.getText();
        cnh_funcionario = cbCnhCad.getSelectedItem().toString();
        contrato_funcionario = cbContratoCad.getSelectedItem().toString();
        cpf_funcionario = txtCpfCad.getText();
        email_funcionario = txtEmailCad.getText();
        idade_funcionario = txtIdadeCad.getText();
        rg_funcionario = txtRgCad.getText();
        setor_funcionario = cbSetorCad.getSelectedItem().toString();
        sexo_funcionario = cbSexoCad.getSelectedItem().toString();
        tel_funcionario = txtTelCad.getText();
        UsuarioDTO objusuariodto = new UsuarioDTO();
        objusuariodto.setNome_funcionario(nome_funcionario);
        objusuariodto.setEndereco_funcionario(endereco_funcionario);
        objusuariodto.setCargo_funcionario(cargo_funcionario);
        objusuariodto.setCel_funcionario(cel_funcionario);
        objusuariodto.setCnh_funcionario(cnh_funcionario);
        objusuariodto.setContrato_funcionario(contrato_funcionario);
        objusuariodto.setCpf_funcionario(cpf_funcionario);
        objusuariodto.setEmail_funcionario(email_funcionario);
        objusuariodto.setIdade_funcionario(idade_funcionario);
        objusuariodto.setRg_funcionario(rg_funcionario);
        objusuariodto.setSetor_funcionario(setor_funcionario);
        objusuariodto.setSexo_funcionario(sexo_funcionario);
        objusuariodto.setTel_funcionario(tel_funcionario);
        UsuarioDAO objusuariodao = new UsuarioDAO();
        objusuariodao.cadastrarFuncionario(objusuariodto);
        txtNomeCad.setText("");
        txtEndCad.setText("");
        listarValores();
        cbSexoCad.setSelectedItem("Feminino");
        cbCargoCad.setSelectedItem("Recepcionista");
        txtCpfCad.setText("");
        txtRgCad.setText("");
        cbCnhCad.setSelectedItem("A");
        txtTelCad.setText("");
        txtCelCad.setText("");
        cbSetorCad.setSelectedItem("Técnico");
        txtIdadeCad.setText("");
        txtEmailCad.setText("");
        cbContratoCad.setSelectedItem("CLT");
    }//GEN-LAST:event_btnCadastroSistemaActionPerformed

    private void txtNomeCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeCadActionPerformed

    private void txtEndCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEndCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEndCadActionPerformed

    private void btnCarregarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarCamposActionPerformed
        CarregarCampos();
    }//GEN-LAST:event_btnCarregarCamposActionPerformed

    private void btnLimparValoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparValoresActionPerformed
        txtNomeCad.setText("");
        txtEndCad.setText("");
        txtNomeCad.requestFocus();
        cbSexoCad.setSelectedItem("Feminino");
        cbCargoCad.setSelectedItem("Recepcionista");
        txtCpfCad.setText("");
        txtRgCad.setText("");
        cbCnhCad.setSelectedItem("A");
        txtTelCad.setText("");
        txtCelCad.setText("");
        cbSetorCad.setSelectedItem("Técnico");
        txtIdadeCad.setText("");
        txtEmailCad.setText("");
        cbContratoCad.setSelectedItem("CLT");
    }//GEN-LAST:event_btnLimparValoresActionPerformed

    private void btnAlterarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarCamposActionPerformed
        AlterarFuncionarios();
        listarValores();
        txtNomeCad.setText("");
        txtEndCad.setText("");
        txtNomeCad.requestFocus();
        cbSexoCad.setSelectedItem("Feminino");
        cbCargoCad.setSelectedItem("Recepcionista");
        txtCpfCad.setText("");
        txtRgCad.setText("");
        cbCnhCad.setSelectedItem("A");
        txtTelCad.setText("");
        txtCelCad.setText("");
        cbSetorCad.setSelectedItem("Técnico");
        txtIdadeCad.setText("");
        txtEmailCad.setText("");
        cbContratoCad.setSelectedItem("CLT");
    }//GEN-LAST:event_btnAlterarCamposActionPerformed

    private void btnExcluirRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirRegistrosActionPerformed
        ExcluirFuncionario();
        listarValores();
        txtNomeCad.setText("");
        txtEndCad.setText("");
        txtNomeCad.requestFocus();
        cbSexoCad.setSelectedItem("Feminino");
        cbCargoCad.setSelectedItem("Recepcionista");
        txtCpfCad.setText("");
        txtRgCad.setText("");
        cbCnhCad.setSelectedItem("A");
        txtTelCad.setText("");
        txtCelCad.setText("");
        cbSetorCad.setSelectedItem("Técnico");
        txtIdadeCad.setText("");
        txtEmailCad.setText("");
        cbContratoCad.setSelectedItem("CLT");
        
    }//GEN-LAST:event_btnExcluirRegistrosActionPerformed

    private void btnExcluirTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirTudoActionPerformed
        ExcluirTudo();
        listarValores();
        txtNomeCad.setText("");
        txtEndCad.setText("");
        txtNomeCad.requestFocus();
    }//GEN-LAST:event_btnExcluirTudoActionPerformed

    private void txtCpfCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfCadActionPerformed

    private void txtRgCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRgCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRgCadActionPerformed

    private void txtTelCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelCadActionPerformed

    private void txtCelCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelCadActionPerformed

    private void txtIdadeCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdadeCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdadeCadActionPerformed

    private void txtEmailCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailCadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCadastroVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCadastroVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCadastroVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCadastroVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCadastroVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnAlterarCampos;
    private java.awt.Button btnCadastroSistema;
    private java.awt.Button btnCarregarCampos;
    private java.awt.Button btnExcluirRegistros;
    private java.awt.Button btnExcluirTudo;
    private java.awt.Button btnLimparValores;
    private javax.swing.JComboBox<String> cbCargoCad;
    private javax.swing.JComboBox<String> cbCnhCad;
    private javax.swing.JComboBox<String> cbContratoCad;
    private javax.swing.JComboBox<String> cbSetorCad;
    private javax.swing.JComboBox<String> cbSexoCad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private java.awt.Label label1;
    private java.awt.Label label26;
    private java.awt.Label label27;
    private java.awt.Label label28;
    private java.awt.Label label29;
    private java.awt.Label label30;
    private java.awt.Label label31;
    private java.awt.Label label32;
    private java.awt.Label label33;
    private java.awt.Label label34;
    private java.awt.Label label35;
    private java.awt.Label label36;
    private java.awt.Label label37;
    private java.awt.Label label6;
    private com.raven.swing.RoundPanel roundPanel1;
    private com.raven.swing.RoundPanel roundPanel2;
    private java.awt.TextField txtCelCad;
    private java.awt.TextField txtCpfCad;
    private java.awt.TextField txtEmailCad;
    private java.awt.TextField txtEndCad;
    private java.awt.TextField txtIdadeCad;
    private java.awt.TextField txtNomeCad;
    private java.awt.TextField txtRgCad;
    private java.awt.TextField txtTelCad;
    // End of variables declaration//GEN-END:variables
    private void listarValores(){
        try{
            UsuarioDAO objusuariodao = new UsuarioDAO();
            DefaultTableModel model = (DefaultTableModel) jTable.getModel();
            model.setNumRows(0);
            ArrayList<UsuarioDTO> lista = objusuariodao.PesquisarFuncionario();
            for(int num = 0; num < lista.size(); num++){
                model.addRow(new Object[]{
                   lista.get(num).getId(),
                   lista.get(num).getNome_funcionario(),
                   lista.get(num).getEndereco_funcionario(),
                   lista.get(num).getSexo_funcionario(),
                   lista.get(num).getCargo_funcionario(),
                   lista.get(num).getCpf_funcionario(),
                   lista.get(num).getRg_funcionario(),
                   lista.get(num).getCnh_funcionario(),
                   lista.get(num).getTel_funcionario(),
                   lista.get(num).getCel_funcionario(),
                   lista.get(num).getSetor_funcionario(),
                   lista.get(num).getIdade_funcionario(),
                   lista.get(num).getEmail_funcionario(),
                   lista.get(num).getContrato_funcionario(),
                });
            }
        }catch (Exception erro){
            JOptionPane.showMessageDialog(null, "Listar Valores VIEW: " + erro);
        }
    }
    private void CarregarCampos(){
        int setar = jTable.getSelectedRow();
        txtNomeCad.setText(jTable.getModel().getValueAt(setar, 1).toString());
        txtEndCad.setText(jTable.getModel().getValueAt(setar, 2).toString());
        cbSexoCad.setSelectedItem(jTable.getModel().getValueAt(setar, 3).toString());
        cbCargoCad.setSelectedItem(jTable.getModel().getValueAt(setar, 4).toString());
        txtCpfCad.setText(jTable.getModel().getValueAt(setar, 5).toString());
        txtRgCad.setText(jTable.getModel().getValueAt(setar, 6).toString());
        cbCnhCad.setSelectedItem(jTable.getModel().getValueAt(setar, 7).toString());
        txtTelCad.setText(jTable.getModel().getValueAt(setar, 8).toString());
        txtCelCad.setText(jTable.getModel().getValueAt(setar, 9).toString());
        cbSetorCad.setSelectedItem(jTable.getModel().getValueAt(setar, 10).toString());
        txtIdadeCad.setText(jTable.getModel().getValueAt(setar, 11).toString());
        txtEmailCad.setText(jTable.getModel().getValueAt(setar, 12).toString());
        cbContratoCad.setSelectedItem(jTable.getModel().getValueAt(setar, 13).toString());
        
        
    }
    private void AlterarFuncionarios(){
        String nome_funcionario, endereco_funcionario;
        String cargo_funcionario, cel_funcionario, cnh_funcionario, contrato_funcionario, cpf_funcionario, email_funcionario, idade_funcionario, rg_funcionario, setor_funcionario, sexo_funcionario, tel_funcionario;
        nome_funcionario = txtNomeCad.getText();
        endereco_funcionario = txtEndCad.getText();
        cargo_funcionario = cbCargoCad.getSelectedItem().toString();
        cel_funcionario = txtCelCad.getText();
        cnh_funcionario = cbCnhCad.getSelectedItem().toString();
        contrato_funcionario = cbContratoCad.getSelectedItem().toString();
        cpf_funcionario = txtCpfCad.getText();
        email_funcionario = txtEmailCad.getText();
        idade_funcionario = txtIdadeCad.getText();
        rg_funcionario = txtRgCad.getText();
        setor_funcionario = cbSetorCad.getSelectedItem().toString();
        sexo_funcionario = cbSexoCad.getSelectedItem().toString();
        tel_funcionario = txtTelCad.getText();
        UsuarioDTO objusuariodto = new UsuarioDTO();
        objusuariodto.setNome_funcionario(nome_funcionario);
        objusuariodto.setEndereco_funcionario(endereco_funcionario);
        objusuariodto.setCargo_funcionario(cargo_funcionario);
        objusuariodto.setCel_funcionario(cel_funcionario);
        objusuariodto.setCnh_funcionario(cnh_funcionario);
        objusuariodto.setContrato_funcionario(contrato_funcionario);
        objusuariodto.setCpf_funcionario(cpf_funcionario);
        objusuariodto.setEmail_funcionario(email_funcionario);
        objusuariodto.setIdade_funcionario(idade_funcionario);
        objusuariodto.setRg_funcionario(rg_funcionario);
        objusuariodto.setSetor_funcionario(setor_funcionario);
        objusuariodto.setSexo_funcionario(sexo_funcionario);
        objusuariodto.setTel_funcionario(tel_funcionario);
        UsuarioDAO objusuariodao = new UsuarioDAO();
        objusuariodao.alterarFuncionario(objusuariodto);
    }
    private void ExcluirFuncionario(){
        String nome_funcionario, endereco_funcionario;
        String cargo_funcionario, cel_funcionario, cnh_funcionario, contrato_funcionario, cpf_funcionario, email_funcionario, idade_funcionario, rg_funcionario, setor_funcionario, sexo_funcionario, tel_funcionario;
        nome_funcionario = txtNomeCad.getText();
        endereco_funcionario = txtEndCad.getText();
        cargo_funcionario = cbCargoCad.getSelectedItem().toString();
        cel_funcionario = txtCelCad.getText();
        cnh_funcionario = cbCnhCad.getSelectedItem().toString();
        contrato_funcionario = cbContratoCad.getSelectedItem().toString();
        cpf_funcionario = txtCpfCad.getText();
        email_funcionario = txtEmailCad.getText();
        idade_funcionario = txtIdadeCad.getText();
        rg_funcionario = txtRgCad.getText();
        setor_funcionario = cbSetorCad.getSelectedItem().toString();
        sexo_funcionario = cbSexoCad.getSelectedItem().toString();
        tel_funcionario = txtTelCad.getText();
        UsuarioDTO objusuariodto = new UsuarioDTO();
        objusuariodto.setNome_funcionario(nome_funcionario);
        objusuariodto.setEndereco_funcionario(endereco_funcionario);
        objusuariodto.setCargo_funcionario(cargo_funcionario);
        objusuariodto.setCel_funcionario(cel_funcionario);
        objusuariodto.setCnh_funcionario(cnh_funcionario);
        objusuariodto.setContrato_funcionario(contrato_funcionario);
        objusuariodto.setCpf_funcionario(cpf_funcionario);
        objusuariodto.setEmail_funcionario(email_funcionario);
        objusuariodto.setIdade_funcionario(idade_funcionario);
        objusuariodto.setRg_funcionario(rg_funcionario);
        objusuariodto.setSetor_funcionario(setor_funcionario);
        objusuariodto.setSexo_funcionario(sexo_funcionario);
        objusuariodto.setTel_funcionario(tel_funcionario);
        UsuarioDAO objusuariodao = new UsuarioDAO();
        objusuariodao.excluirFuncionario(objusuariodto);
    }
    private void ExcluirTudo(){
        UsuarioDTO objusuariodto = new UsuarioDTO();
        UsuarioDAO objusuariodao = new UsuarioDAO();
        objusuariodao.excluirTudo(objusuariodto);
    }
}
